function(omni_test_warnings target)
  target_compile_options(${target} PRIVATE -Wall -Wextra -Werror ${ARGN} -UNDEBUG)
endfunction()

enable_testing()
add_executable(test_mixer_control tests/test_mixer_control.c src/mixer_control.c src/source_mix.c)
target_include_directories(test_mixer_control PRIVATE include)
omni_test_warnings(test_mixer_control -Wconversion)
add_test(NAME source_bias_control COMMAND test_mixer_control)
add_executable(test_source_mix tests/test_source_mix.c src/source_mix.c)
target_include_directories(test_source_mix PRIVATE include)
omni_test_warnings(test_source_mix -Wconversion)
add_test(NAME source_bias_pcm COMMAND test_source_mix)
add_executable(test_home_ui tests/test_home_ui.c src/home_ui.c src/eq_response.c)
target_include_directories(test_home_ui PRIVATE include)
omni_test_warnings(test_home_ui -Wconversion)
add_test(NAME technical_oled_render COMMAND test_home_ui)
add_executable(test_headset_gain tests/test_headset_gain.c src/headset_gain.c src/interchip.c)
target_include_directories(test_headset_gain PRIVATE include)
omni_test_warnings(test_headset_gain -Wconversion)
add_test(NAME headset_gain_protocol COMMAND test_headset_gain)
add_executable(test_headset_volume tests/test_headset_volume.c src/headset_volume.c src/native_gain_curve.c)
target_include_directories(test_headset_volume PRIVATE include)
omni_test_warnings(test_headset_volume -Wconversion)
add_test(NAME headset_volume_curve COMMAND test_headset_volume)
add_executable(test_remote_menu tests/test_remote_menu.c src/remote_menu.c src/interchip.c)
target_include_directories(test_remote_menu PRIVATE include)
omni_test_warnings(test_remote_menu -Wconversion)
add_test(NAME remote_menu_coordination COMMAND test_remote_menu)
add_executable(test_dsp_settings tests/test_dsp_settings.c src/dsp_settings.c src/interchip.c)
target_include_directories(test_dsp_settings PRIVATE include)
omni_test_warnings(test_dsp_settings -Wconversion)
add_test(NAME dsp_settings_contract COMMAND test_dsp_settings)
add_executable(test_dsp_meter tests/test_dsp_meter.c src/dsp_meter.c src/interchip.c)
target_include_directories(test_dsp_meter PRIVATE include)
omni_test_warnings(test_dsp_meter -Wconversion)
add_test(NAME dsp_meter_polling COMMAND test_dsp_meter)
add_executable(test_headset_battery tests/test_headset_battery.c src/headset_battery.c src/interchip.c)
target_include_directories(test_headset_battery PRIVATE include)
omni_test_warnings(test_headset_battery -Wconversion)
add_test(NAME headset_battery_protocol COMMAND test_headset_battery)
add_executable(test_headset_query tests/test_headset_query.c src/headset_query.c src/interchip.c)
target_include_directories(test_headset_query PRIVATE include)
omni_test_warnings(test_headset_query -Wconversion)
add_test(NAME headset_query_whitelist COMMAND test_headset_query)
add_executable(test_native_battery_adapter tests/test_native_battery_adapter.c
  src/native_gain_adapter.c src/native_gain.c src/native_gain_curve.c src/headset_gain.c src/headset_volume.c
  src/dsp_gain_trial.c src/headset_battery.c src/headset_query.c src/dsp_meter.c src/dsp_settings.c src/remote_menu.c src/interchip.c)
target_include_directories(test_native_battery_adapter PRIVATE tests/dsp_volume_probe_stubs include)
omni_test_warnings(test_native_battery_adapter -Wconversion)
add_test(NAME native_battery_arbitration COMMAND test_native_battery_adapter)
add_executable(test_mixer_ui tests/test_mixer_ui.c src/settings_menu.c src/eq_menu.c src/mixer_ui.c src/source_mix.c src/home_ui.c src/eq_response.c src/mixer.c src/native_gain_curve.c src/volume_scale.c src/controls.c src/control_action.c)
target_include_directories(test_mixer_ui PRIVATE include)
omni_test_warnings(test_mixer_ui -Wconversion)
add_test(NAME mixer_ui_navigation COMMAND test_mixer_ui)
add_executable(test_mixer tests/test_mixer.c src/mixer.c)
target_include_directories(test_mixer PRIVATE include)
omni_test_warnings(test_mixer -Wconversion)
add_test(NAME mixer_linked_independent COMMAND test_mixer)
add_executable(test_mixer_transport tests/test_mixer_transport.c src/native_gain.c src/native_gain_curve.c src/dsp_gain_trial.c src/interchip.c)
target_include_directories(test_mixer_transport PRIVATE include)
omni_test_warnings(test_mixer_transport -Wconversion)
add_test(NAME mixer_transport_coalescing COMMAND test_mixer_transport)
add_executable(test_ui_idle tests/test_ui_idle.c)
target_include_directories(test_ui_idle PRIVATE include)
omni_test_warnings(test_ui_idle -Wconversion)
add_test(NAME ui_idle_timeout COMMAND test_ui_idle)
add_executable(test_charger_policy tests/test_charger_policy.c src/charger_policy.c)
target_include_directories(test_charger_policy PRIVATE include)
omni_test_warnings(test_charger_policy -Wconversion)
add_test(NAME charger_live_profile_policy COMMAND test_charger_policy)
add_executable(test_usb_iso_banks tests/test_usb_iso_banks.c src/usb_iso_banks.c)
target_include_directories(test_usb_iso_banks PRIVATE include)
omni_test_warnings(test_usb_iso_banks -Wconversion)
add_test(NAME usb_iso_bank_ownership COMMAND test_usb_iso_banks)
add_executable(test_dsp_volume tests/test_dsp_volume.c src/dsp_volume.c src/interchip.c)
target_include_directories(test_dsp_volume PRIVATE include)
omni_test_warnings(test_dsp_volume -Wconversion)
add_test(NAME dsp_volume_query_contract COMMAND test_dsp_volume)
add_executable(test_dsp_gain_trial tests/test_dsp_gain_trial.c src/dsp_gain_trial.c src/interchip.c)
target_include_directories(test_dsp_gain_trial PRIVATE include)
omni_test_warnings(test_dsp_gain_trial -Wconversion)
add_test(NAME dsp_gain_trial_contract COMMAND test_dsp_gain_trial)
add_executable(test_native_gain tests/test_native_gain.c src/native_gain.c src/native_gain_curve.c src/dsp_gain_trial.c src/interchip.c)
target_include_directories(test_native_gain PRIVATE include)
omni_test_warnings(test_native_gain -Wconversion)
add_test(NAME native_gain_coalescing COMMAND test_native_gain)
add_executable(test_dsp_volume_probe tests/test_dsp_volume_probe.c
  src/dsp_volume_probe.c src/dsp_volume.c src/dsp_gain_trial.c src/interchip.c)
target_include_directories(test_dsp_volume_probe PRIVATE tests/dsp_volume_probe_stubs include)
omni_test_warnings(test_dsp_volume_probe -Wconversion)
foreach(scenario RANGE 0 8)
  add_test(NAME dsp_volume_uart_lifecycle_${scenario} COMMAND test_dsp_volume_probe ${scenario})
endforeach()
add_executable(test_audio_queue tests/test_audio_queue.c src/audio_queue.c)
target_include_directories(test_audio_queue PRIVATE include)
omni_test_warnings(test_audio_queue -Wconversion)
add_test(NAME audio_queue_contracts COMMAND test_audio_queue)
add_executable(test_audio_rate tests/test_audio_rate.c src/audio_rate.c)
target_include_directories(test_audio_rate PRIVATE include)
omni_test_warnings(test_audio_rate -Wconversion)
target_link_libraries(test_audio_rate PRIVATE m)
add_test(NAME audio_rate_control COMMAND test_audio_rate)
add_executable(test_audio_delivery tests/test_audio_delivery.c)
target_include_directories(test_audio_delivery PRIVATE include)
omni_test_warnings(test_audio_delivery -Wconversion)
add_test(NAME audio_delivery_observations COMMAND test_audio_delivery)
add_executable(test_sof_capture tests/test_sof_capture.c src/sof_capture.c)
target_include_directories(test_sof_capture PRIVATE include)
omni_test_warnings(test_sof_capture -Wconversion)
add_test(NAME bounded_sof_capture COMMAND test_sof_capture)
add_executable(test_core tests/test_core.c)
target_link_libraries(test_core PRIVATE omni_core)
omni_test_warnings(test_core)
add_test(NAME core_contracts COMMAND test_core)
add_executable(test_boot_ack tests/test_boot_ack.c)
target_link_libraries(test_boot_ack PRIVATE omni_core)
omni_test_warnings(test_boot_ack)
add_test(NAME boot_ack_contracts COMMAND test_boot_ack)
add_executable(test_audio_descriptors tests/test_audio_descriptors.c src/audio_descriptors.c)
target_include_directories(test_audio_descriptors PRIVATE include)
omni_test_warnings(test_audio_descriptors)
add_test(NAME audio_descriptors COMMAND test_audio_descriptors)
add_executable(test_display tests/test_display.c src/display.c)
target_include_directories(test_display PRIVATE include)
omni_test_warnings(test_display -Wconversion)
add_test(NAME display_state_machine COMMAND test_display)
add_executable(test_rotary tests/test_rotary.c src/rotary.c)
target_include_directories(test_rotary PRIVATE include)
omni_test_warnings(test_rotary -Wconversion)
add_test(NAME rotary_transitions COMMAND test_rotary)
add_executable(test_controls tests/test_controls.c src/controls.c)
target_include_directories(test_controls PRIVATE include)
omni_test_warnings(test_controls -Wconversion)
add_test(NAME shared_controls COMMAND test_controls)
add_executable(test_control_action tests/test_control_action.c src/control_action.c src/controls.c)
target_include_directories(test_control_action PRIVATE include)
omni_test_warnings(test_control_action -Wconversion)
add_test(NAME control_action_normalization COMMAND test_control_action)
add_executable(test_interchip tests/test_interchip.c src/interchip.c)
target_include_directories(test_interchip PRIVATE include)
omni_test_warnings(test_interchip -Wconversion)
add_test(NAME interchip_framing COMMAND test_interchip)
add_executable(test_mcu2_controls tests/test_mcu2_controls.c src/mcu2_controls.c)
target_include_directories(test_mcu2_controls PRIVATE include)
omni_test_warnings(test_mcu2_controls -Wconversion)
add_test(NAME mcu2_passive_controls COMMAND test_mcu2_controls)
add_executable(test_mcu2_runtime tests/test_mcu2_runtime.c src/mcu2_runtime.c)
target_include_directories(test_mcu2_runtime PRIVATE include)
omni_test_warnings(test_mcu2_runtime -Wconversion)
add_test(NAME mcu2_persistent_runtime COMMAND test_mcu2_runtime)
add_executable(test_mcu2_link tests/test_mcu2_link.c src/mcu2_link.c)
target_include_directories(test_mcu2_link PRIVATE include)
omni_test_warnings(test_mcu2_link -Wconversion)
add_test(NAME mcu2_status_transaction COMMAND test_mcu2_link)
add_executable(test_audio_bus tests/test_audio_bus.c src/audio_bus.c)
target_include_directories(test_audio_bus PRIVATE include)
omni_test_warnings(test_audio_bus -Wconversion)
add_test(NAME audio_bus_contracts COMMAND test_audio_bus)
add_executable(test_audio_mode tests/test_audio_mode.c src/audio_mode.c)
target_include_directories(test_audio_mode PRIVATE include)
omni_test_warnings(test_audio_mode -Wconversion)
add_test(NAME audio_mode_sequence COMMAND test_audio_mode)
add_executable(test_dsp_link tests/test_dsp_link.c src/dsp_link.c src/interchip.c)
target_include_directories(test_dsp_link PRIVATE include)
omni_test_warnings(test_dsp_link -Wconversion)
add_test(NAME dsp_status_transaction COMMAND test_dsp_link)
add_executable(test_dsp_capture tests/test_dsp_capture.c src/dsp_capture.c src/interchip.c)
target_include_directories(test_dsp_capture PRIVATE include)
omni_test_warnings(test_dsp_capture -Wconversion)
add_test(NAME dsp_passive_capture COMMAND test_dsp_capture)
add_executable(test_audio_clock tests/test_audio_clock.c src/audio_clock.c)
target_include_directories(test_audio_clock PRIVATE include)
omni_test_warnings(test_audio_clock -Wconversion)
add_test(NAME bounded_audio_clock COMMAND test_audio_clock)
add_executable(test_audio_clock_binding tests/test_audio_clock_binding.c src/audio_clock.c src/audio_clock_lpc5528.c)
target_include_directories(test_audio_clock_binding PRIVATE include)
omni_test_warnings(test_audio_clock_binding -Wconversion)
add_test(NAME audio_clock_binding COMMAND test_audio_clock_binding)
add_executable(test_usb_selector tests/test_usb_selector.c)
omni_test_warnings(test_usb_selector -Wconversion)
add_test(NAME usb_selector COMMAND test_usb_selector)

add_executable(test_settings_menu tests/test_settings_menu.c src/settings_menu.c src/eq_menu.c src/mixer_ui.c src/source_mix.c src/home_ui.c src/eq_response.c src/mixer.c src/native_gain_curve.c src/volume_scale.c)
target_include_directories(test_settings_menu PRIVATE include)
omni_test_warnings(test_settings_menu -Wconversion)
add_test(NAME settings_menu_navigation COMMAND test_settings_menu)

add_executable(test_settings_menu_native tests/test_settings_menu_native.c src/settings_menu_native.c)
target_include_directories(test_settings_menu_native PRIVATE include)
omni_test_warnings(test_settings_menu_native -Wconversion)
add_test(NAME settings_menu_native COMMAND test_settings_menu_native)

add_executable(test_eq_native tests/test_eq_native.c src/settings_menu_native.c src/dsp_settings.c src/interchip.c)
target_include_directories(test_eq_native PRIVATE include)
omni_test_warnings(test_eq_native -Wconversion)
add_test(NAME eq_native COMMAND test_eq_native)
add_executable(test_eq_menu tests/test_eq_menu.c src/eq_menu.c)
target_include_directories(test_eq_menu PRIVATE include)
omni_test_warnings(test_eq_menu -Wconversion)
add_test(NAME eq_menu COMMAND test_eq_menu)

add_executable(test_eq_graph tests/test_eq_graph.c src/eq_response.c src/native_gain_curve.c src/volume_scale.c)
target_include_directories(test_eq_graph PRIVATE include)
omni_test_warnings(test_eq_graph -Wconversion)
add_test(NAME eq_graph COMMAND test_eq_graph)

add_executable(test_eq_response tests/test_eq_response.c src/eq_response.c)
target_include_directories(test_eq_response PRIVATE include)
target_link_libraries(test_eq_response PRIVATE m)
omni_test_warnings(test_eq_response -Wconversion)
add_test(NAME eq_response COMMAND test_eq_response)
