"""Generate integer-only EQ preview tables; no device or network access."""
import math
from pathlib import Path

def generate():
    tables = [
        ('uint32_t', 'warp', [round(math.tan(math.pi * hz / 48000) * (1 << 24)) for hz in range(0, 20001, 40)]),
        ('uint32_t', 'amplitude', [round(10 ** ((gain - 120) / 400) * (1 << 20)) for gain in range(248)]),
        ('uint16_t', 'log_fraction', [round(math.log2(1 + i / 256) * 4096) for i in range(257)]),
        ('uint16_t', 'plot_frequency', [round(20 * 1000 ** (i / 103)) for i in range(104)])]
    lines = ['/* Generated by tools/generate_eq_response_tables.py. */']
    for kind, name, values in tables:
        lines.append(f'static const {kind} {name}[{len(values)}]={{')
        for start in range(0, len(values), 12):
            lines.append('    ' + ','.join(str(v) + 'u' for v in values[start:start+12]) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    (Path(__file__).resolve().parents[1] / 'src/eq_response_tables.inc').write_text(generate())
