#ifndef OMNI_AUDIO_USB_LAYOUT_H
#define OMNI_AUDIO_USB_LAYOUT_H
enum {
    OMNI_PLAYBACK_AC_INTERFACE=0,
    OMNI_PLAYBACK_AS_INTERFACE=1,
    OMNI_MICROPHONE_AC_INTERFACE=2,
    OMNI_MICROPHONE_AS_INTERFACE=3,
    OMNI_HID_INTERFACE=4,
    OMNI_USB_INTERFACE_COUNT=5,
    OMNI_AUDIO_CONFIG_LENGTH=355,
    OMNI_HID_DESCRIPTOR_OFFSET=339
};
#endif
